### ISSUE TITLE
Git and Flatiron

### ISSUE THREAD

**Issue by boom100100** [learn-co-curriculum/git-basics-lab#10]
I haven't found clear instructions on how to have my own IDE record lab progress throughout this course. I can fork and clone, but the learn site doesn't show that it happened. And, obviously, my terminal isn't able to recognize the learn command. Is this functionality not possible?

**Comment by maxwellbenton** [comment]
Hi @boom100100,

The first portion of the online course is designed to work with the in-browser IDE, and it is recommended students use this until they get to Sinatra. Later parts of the course will require setting up the local environment to use `learn`, which is part of the `learn-co` gem.

This article explains a bit further and includes a link to the instructions for local environment setup: https://help.learn.co/en/articles/1394611-when-should-i-set-up-a-local-environment

Hope this helps!
