### ISSUE TITLE
Lab design leads often leads to git issues, especially for IDE users 

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/git-basics-lab#2]
I have worked with many students that get lost trying to debug github issues due to running git commands in the wrong directory in the IDE (in the parent directory rather than in the my-repository directory they have created). 

This often leads to them spending a very long time on this lab trying to debug complex git issues, which detracts from what they should have learned from this lesson. 

I think removing the instruction to switch back and forth between the parent directory and `my-repository` to run the tests after every step and being more explicit about where each commend should be run should help quite a bit.

**Comment by sgharms** [comment]
@kwebster2 I'm going to close the issue, but I have PR #3 open and would appreciate your verification of the solution we're proposing. LMK!
